name: subrational
description:
url: http://subrational.com
exclude:  [Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, vendor, gems, publish]
highlighter: pygments
permalink: pretty
sass:
  syntax: scss
  style: compressed
